Repository MTalhaofc/HacktoberFest-2024, pull requests merged in 2024-10, with the labels that each got.

#17 Create SnakeGame.py
  PYTHON/SnakeGame.py
Labels: hacktoberfest, hacktoberfest-2024

#19 Create GuessNumber.java
  JAVA/GuessNumber.java
Labels: hacktoberfest, hacktoberfest-2024

#22 Added queue and stack implementation using C
  C/QueueWithArrays.c
  C/QueueWithLinkedList.c
  C/StackWithArrays.c
  C/StackWithLinkedList.c
Labels: hacktoberfest-2024

#20 Create Maze Runner.cpp
  C++/Maze Runner.cpp
Labels: hacktoberfest, hacktoberfest-2024

#24 Linked List Concept using C++
  C++/CircularLinkedList.cpp
  C++/DoublyLinkedList.cpp
  C++/SinglyLinkedList.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#26 Added Memory Game
  FRONTEND-PROJECTS/Memory Game/app.js
  FRONTEND-PROJECTS/Memory Game/index.html
  FRONTEND-PROJECTS/Memory Game/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#27 Create RotateArray.java
  JAVA/RotateArray.java
Labels: hacktoberfest, hacktoberfest-2024

#28 Created a python RPG 1v1 style game "template"
  PYTHON/RPG style 1v1.py
Labels: hacktoberfest, hacktoberfest-2024

#29 Sudoku in Python
  PYTHON/Sudoku in Python
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#33 Python fie sorter
  PYTHON/sorter_tool.py
  PYTHON/wordlist.txt
Labels: hacktoberfest, hacktoberfest-2024

#31 Add initial index.html file for project setup
  FRONTEND-PROJECTS/Task-Manager/app.js
  FRONTEND-PROJECTS/Task-Manager/index.html
  FRONTEND-PROJECTS/Task-Manager/style.css
Labels: hacktoberfest, hacktoberfest-2024

#35 A game center
  FRONTEND-PROJECTS/index.html
  FRONTEND-PROJECTS/script.js
  FRONTEND-PROJECTS/style.css
Labels: hacktoberfest, hacktoberfest-2024

#37 Rock,_Paper _Scissors Game in python
  PYTHON/RockPaperScissors.py
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#38 Added Rock-Paper-Scissor.cpp
  C++/rock-paper-scissor.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#42 BMI calculator in Core PHP
  PHP/BMI Calculator/index.php
  PHP/BMI Calculator/readme.md
  PHP/BMI Calculator/style.css
  PHP/Phpfile.php
  PHP/readme.md
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#41 Python shape recoginition
  PYTHON/8.jpeg
  PYTHON/ShapeRecoginization.py
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#40 Create sudoku-solver.cpp
  C++/sudoku-solver.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#39 Create egg_puzzle.cpp
  C++/egg_puzzle.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#43 Added Number Plate Recognition
  PYTHON/Number Plate Recognition/NumPlateRecogniton.ipynb
  PYTHON/Number Plate Recognition/image1.jpg
  PYTHON/Number Plate Recognition/image2.jpg
  PYTHON/Number Plate Recognition/image3.jpg
  PYTHON/Number Plate Recognition/image4.jpg
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#46 Vehicle number plate recognition using EasyOCR
  NumberPlateRecog/Numberplaterecog.ipynb
  NumberPlateRecog/Readme.txt
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#44 Added "Dashboard UI" project in frontend projects
  FRONTEND-PROJECTS/Dashbord UI/apps.png
  FRONTEND-PROJECTS/Dashbord UI/collapse.png
  FRONTEND-PROJECTS/Dashbord UI/create.png
  FRONTEND-PROJECTS/Dashbord UI/feedback.png
  FRONTEND-PROJECTS/Dashbord UI/help.png
  FRONTEND-PROJECTS/Dashbord UI/index.css
  FRONTEND-PROJECTS/Dashbord UI/index.html
  FRONTEND-PROJECTS/Dashbord UI/index.js
  FRONTEND-PROJECTS/Dashbord UI/intro.png
  FRONTEND-PROJECTS/Dashbord UI/my_project.png
  FRONTEND-PROJECTS/Dashbord UI/package-lock.json
  FRONTEND-PROJECTS/Dashbord UI/package.json
  FRONTEND-PROJECTS/Dashbord UI/sample_project.png
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#51 Frontend Project Added
  FRONTEND-PROJECTS/rock_paper_scissors/README.md
  FRONTEND-PROJECTS/rock_paper_scissors/index.html
  FRONTEND-PROJECTS/rock_paper_scissors/main.js
  FRONTEND-PROJECTS/rock_paper_scissors/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#50 feat: add some O(n2) sort algorithms in C
  C/BubbleSort.c
  C/InsertionSort.c
  C/SelectionSort.c
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#48 Added insertion sort in java
  JAVA/insertion sort
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#47 added two important alogrithms used in programming
  C++/KadaneAlgorithm.cpp
  C++/KahnAlgorithm.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#52 Create 2Sum.cpp
  C++/2Sum.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#53 Created a matrix program.
  JAVA/Matrix.java
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#54 problem added: find the longest substring without repeating characters.
  C++/longest_substring.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#55 project added
  FRONTEND-PROJECTS/06_ToDo_UsingContextAPIandLocalStorage/.eslintrc.cjs
  FRONTEND-PROJECTS/06_ToDo_UsingContextAPIandLocalStorage/.gitignore
  FRONTEND-PROJECTS/06_ToDo_UsingContextAPIandLocalStorage/README.md
  FRONTEND-PROJECTS/06_ToDo_UsingContextAPIandLocalStorage/index.html
  FRONTEND-PROJECTS/06_ToDo_UsingContextAPIandLocalStorage/package-lock.json
  FRONTEND-PROJECTS/06_ToDo_UsingContextAPIandLocalStorage/package.json
  FRONTEND-PROJECTS/06_ToDo_UsingContextAPIandLocalStorage/postcss.config.js
  FRONTEND-PROJECTS/06_ToDo_UsingContextAPIandLocalStorage/public/vite.svg
  FRONTEND-PROJECTS/06_ToDo_UsingContextAPIandLocalStorage/src/App.css
  FRONTEND-PROJECTS/06_ToDo_UsingContextAPIandLocalStorage/src/App.jsx
  FRONTEND-PROJECTS/06_ToDo_UsingContextAPIandLocalStorage/src/assets/react.svg
  FRONTEND-PROJECTS/06_ToDo_UsingContextAPIandLocalStorage/src/components/Todoform.jsx
  FRONTEND-PROJECTS/06_ToDo_UsingContextAPIandLocalStorage/src/components/Todoitems.jsx
  FRONTEND-PROJECTS/06_ToDo_UsingContextAPIandLocalStorage/src/components/index.js
  FRONTEND-PROJECTS/06_ToDo_UsingContextAPIandLocalStorage/src/contexts/TodoContext.js
  FRONTEND-PROJECTS/06_ToDo_UsingContextAPIandLocalStorage/src/contexts/index.js
  FRONTEND-PROJECTS/06_ToDo_UsingContextAPIandLocalStorage/src/index.css
  FRONTEND-PROJECTS/06_ToDo_UsingContextAPIandLocalStorage/src/main.jsx
  FRONTEND-PROJECTS/06_ToDo_UsingContextAPIandLocalStorage/tailwind.config.js
  FRONTEND-PROJECTS/06_ToDo_UsingContextAPIandLocalStorage/vite.config.js
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#56 Add matrix multiplication implementation in Java
  JAVA/matrix_multiplication.java
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#60 Simple Expense Tracker in python #49
  PYTHON/SimpleExpenseTracker.py
Labels: good first issue, hacktoberfest, hacktoberfest-2024

#62 feat: Implement PHP Endpoint
  PHP/Etherscan-Endpoint/data/.gitkeep
  PHP/Etherscan-Endpoint/index.php
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#63 Random Password Generator in PHP
  PHP/random-password-generator/generate_password.php
  PHP/random-password-generator/index.html
  PHP/random-password-generator/readme.md
  PHP/random-password-generator/script.js
  PHP/random-password-generator/style.css
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#65 Bulkfilerenametool.py
  PYTHON/Bulkfilerenametool.py
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#68 Added Quick Sort in Java
  JAVA/QuickSort.java
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#66 News App
  PYTHON/main.py
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#71 Create insertionsort.py
  PYTHON/insertionsort.py
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#70 Added
  JAVA/Dijkstra’s algorithm.java
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#72 create selection and bubblesort in python
  PYTHON/bubblesort.py
  PYTHON/selectionsort.py
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#73 Add String ATOI in Java
  JAVA/String_atoi.java
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#89 Merge Sort. Java
  JAVA/Merge Sort.Java
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#87 Hacktoberfest 2024
  FRONTEND-PROJECTS/Calculator/calc.css
  FRONTEND-PROJECTS/Calculator/calc.html
  FRONTEND-PROJECTS/Calculator/calc.js
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#86 Quicksort python
  PYTHON/linkedlist.py
  PYTHON/quicksort.py
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#84 Add files via upload
  Time-Wasters on Social Media/Time-Wasters on Social Media.csv
  Time-Wasters on Social Media/social_media.ipynb
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#74 password check code
  C/password.c
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#77 Created TicTacToe game
  JAVASCRIPT/TicTacToe.html
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#75 Create mergesort.py
  PYTHON/mergesort.py
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#90 Age Calculator in PHP
  PHP/age_calculator/index.php
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#91 feat/Toast
  REACTNATIVE/toastUtil.tsx
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#97 Personalized countdown Time in Javascript
  personalized-countdown-time/index.html
  personalized-countdown-time/readme.md
  personalized-countdown-time/script.js
  personalized-countdown-time/style.css
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#96 Personalized Greeting Card Generator
  Personalized_Greeting_Card_Generator/index.php
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#95 Add files via upload
  C++/segmentTree.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#93 Create Letter Combinations of a Phone Number
  Letter Combinations of a Phone Number
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#100 Issue #78: Implementing Bubble & Insertion sort using Linked Lists.
  C/BubbleSortLinkedList.c
  C/InsertionSortLinkedList.c
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#101 web-calculator-JS
  JAVASCRIPT/README.md
  JAVASCRIPT/index.html
  JAVASCRIPT/main.css
  JAVASCRIPT/main.js
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#102 Create Todo list.html #81
  JAVASCRIPT/Todo list.html
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#123 2641. Cousins in Binary Tree II
  2641. Cousins in Binary Tree II
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#122 Create RadixSort.cpp
  C++/RadixSort.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#121 Added Red black trees
  C/redblacktrees.c
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#120 Keylogger Python Script
  PYTHON/Keylogger/keylogger.py
  PYTHON/Keylogger/readme.md
  PYTHON/Keylogger/requirements.txt
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#116 Wasteage of Time on Social Media
  C++/class&template.cpp
  Time-Wasters on Social Media.csv
  social_media.ipynb
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#113 Added invert no in py
  PYTHON/invertno.py
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#109 Added BST in c
  C/BinarySearchTree.c
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#107 Contact Form in PHP
  Contact Form in PHP/index.html
  Contact Form in PHP/process_form.php
  Contact Form in PHP/readme.md
  Contact Form in PHP/script.js
  Contact Form in PHP/style.css
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#106 Create Routing_in_Express.js
  EXPRESSJS/Routing_in_Express.js
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#125 Create Node-item-hub.js
  NODEJS/Node-item-hub.js
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#128 React_Currency_Converter_App
  REACT/React_Currency_Converter/.gitignore
  REACT/React_Currency_Converter/README.md
  REACT/React_Currency_Converter/eslint.config.js
  REACT/React_Currency_Converter/index.html
  REACT/React_Currency_Converter/package-lock.json
  REACT/React_Currency_Converter/package.json
  REACT/React_Currency_Converter/postcss.config.js
  REACT/React_Currency_Converter/public/vite.svg
  REACT/React_Currency_Converter/src/App.jsx
  REACT/React_Currency_Converter/src/assets/react.svg
  REACT/React_Currency_Converter/src/components/InputBox.jsx
  REACT/React_Currency_Converter/src/components/index.js
  REACT/React_Currency_Converter/src/hooks/useCurrencyInfo.js
  REACT/React_Currency_Converter/src/index.css
  REACT/React_Currency_Converter/src/main.jsx
  REACT/React_Currency_Converter/tailwind.config.js
  REACT/React_Currency_Converter/vite.config.js
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#127 Create new.....cpp
  new.....cpp
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#126 Create Task-Tracker.js
  NODEJS/Task-Tracker.js
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#129 Added different searching algorithms
  JAVA/SearchingAlgorithm/BinarySearch.java
  JAVA/SearchingAlgorithm/ExponentialSearch.java
  JAVA/SearchingAlgorithm/InterpolationSearch.java
  JAVA/SearchingAlgorithm/JumpSearch.java
  JAVA/SearchingAlgorithm/LinearSearch.java
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#131 SelectionSort
  JAVA/selectionsort.java
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#139 Create bubbleSort.java
  JAVA/bubbleSort.java
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#137 Simple Voting System
  Simple_Voting_System/index.php
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#136 Added a code of Big Star to JAVA
  JAVA/BigStar.java
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#135 TransposeMatrix.java
  JAVA/TransposeMatrix.java
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#134 Create BubbleSort.java
  JAVA/BubbleSort.java
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#133 PrimsAlgorithm
  JAVA/primsAlgorithm.java
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#132 matric same or not
  JAVA/are matrix same
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#140 Bredth depth search algorithm uploaded
  JAVA/Bredth_depth_search.java
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#141 Project-added
  FRONTEND-PROJECTS/Random-Password-Generator-main/README.md
  FRONTEND-PROJECTS/Random-Password-Generator-main/copy.png
  FRONTEND-PROJECTS/Random-Password-Generator-main/generate.png
  FRONTEND-PROJECTS/Random-Password-Generator-main/index.html
  FRONTEND-PROJECTS/Random-Password-Generator-main/script.js
  FRONTEND-PROJECTS/Random-Password-Generator-main/style.css
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#150 Diamond Star pattern
  JAVA/Diamond Star pattern
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#145 Added my minimal competitive programming template
  C++/CP-template.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#144 Analog
  Analog_Clock/src/App.css
  Analog_Clock/src/App.js
  Analog_Clock/src/App.test.js
  Analog_Clock/src/components/Box.css
  Analog_Clock/src/components/Box.js
  Analog_Clock/src/index.css
  Analog_Clock/src/index.js
  Analog_Clock/src/logo.svg
  Analog_Clock/src/pages/Clock.css
  Analog_Clock/src/pages/Clock.js
  Analog_Clock/src/pages/Home.css
  Analog_Clock/src/pages/Home.js
  Analog_Clock/src/reportWebVitals.js
  Analog_Clock/src/setupTests.js
  RBAC_SYS/rbac.js
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#160 hollowHourglass
  JAVA/bubbleSort.java
  JAVA/hollowHourglass.java
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#161 Random Password Generator added
  REACT/Password_Generator/.gitignore
  REACT/Password_Generator/README.md
  REACT/Password_Generator/eslint.config.js
  REACT/Password_Generator/index.html
  REACT/Password_Generator/package-lock.json
  REACT/Password_Generator/package.json
  REACT/Password_Generator/postcss.config.js
  REACT/Password_Generator/public/vite.svg
  REACT/Password_Generator/src/App.css
  REACT/Password_Generator/src/App.jsx
  REACT/Password_Generator/src/assets/react.svg
  REACT/Password_Generator/src/index.css
  REACT/Password_Generator/src/main.jsx
  REACT/Password_Generator/tailwind.config.js
  REACT/Password_Generator/vite.config.js
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#157 Create PrintMatrixDiagonal.java
  JAVA/PrintMatrixDiagonal.java
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#163 Create SpiralOrderMatrix.java
  JAVA/SpiralOrderMatrix.java
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#164 Create TwoSum.java
  JAVA/TwoSum.java
Labels: good first issue, hacktoberfest-2024, hacktoberfest-accepted

#165 Theme Switcher added
  REACT/Login_form_profile_component/.eslintrc.cjs
  REACT/Login_form_profile_component/.gitignore
  REACT/Login_form_profile_component/README.md
  REACT/Login_form_profile_component/index.html
  REACT/Login_form_profile_component/package-lock.json
  REACT/Login_form_profile_component/package.json
  REACT/Login_form_profile_component/public/vite.svg
  REACT/Login_form_profile_component/src/App.css
  REACT/Login_form_profile_component/src/App.jsx
  REACT/Login_form_profile_component/src/assets/react.svg
  REACT/Login_form_profile_component/src/components/Login.jsx
  REACT/Login_form_profile_component/src/components/Profile.jsx
  REACT/Login_form_profile_component/src/context/UserContext.js
  REACT/Login_form_profile_component/src/context/UserContextProvider.jsx
  REACT/Login_form_profile_component/src/index.css
  REACT/Login_form_profile_component/src/main.jsx
  REACT/Login_form_profile_component/vite.config.js
  REACT/Theme_Switcher/.eslintrc.cjs
  REACT/Theme_Switcher/.gitignore
  REACT/Theme_Switcher/README.md
  REACT/Theme_Switcher/index.html
  REACT/Theme_Switcher/package-lock.json
  REACT/Theme_Switcher/package.json
  REACT/Theme_Switcher/postcss.config.js
  REACT/Theme_Switcher/public/vite.svg
  REACT/Theme_Switcher/src/App.css
  REACT/Theme_Switcher/src/App.jsx
  REACT/Theme_Switcher/src/assets/react.svg
  REACT/Theme_Switcher/src/components/Card.jsx
  REACT/Theme_Switcher/src/components/ThemeBtn.jsx
  REACT/Theme_Switcher/src/contexts/theme.js
  REACT/Theme_Switcher/src/index.css
  REACT/Theme_Switcher/src/main.jsx
  REACT/Theme_Switcher/tailwind.config.js
  REACT/Theme_Switcher/vite.config.js
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#166 Create PalindromeNumber.java
  JAVA/PalindromeNumber.java
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#146 Emoji Mood Tracker
  Emoji_Mood_Tracker/index.php
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#147 Python game added
  PYTHON/alien-invasion.py
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#167 Update BubbleSort.java
  JAVA/BubbleSort.java
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#149 Added Tic Tac Toe
  JAVASCRIPT/Zerodha Landing Page/index.html
  JAVASCRIPT/Zerodha Landing Page/logo.svg
  JAVASCRIPT/Zerodha Landing Page/photo.png
  TS/Tic-Tac-Toe/index.html
  TS/Tic-Tac-Toe/script.ts
  TS/Tic-Tac-Toe/style.css
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted

#172 Add a star in python
  PYTHON/Star.py
Labels: good first issue, hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted
